name: OpenHRV
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nomkl    # necessary for building with PyInstaller on Windowns, since installing numpy (pyqtgraph dependency) with MKL currently breaks pyinstaller
  - pyqtgraph
  - pyside2
  - pyinstaller    # only for building
  - pip
  - pip:
    - bleak