name: OpenHRV
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nomkl    # necessary to install numpy (pyqtgraph dependency) without MKL, since MKL currently breaks pyinstaller
  - pyqtgraph
  - pyside2
  - pyinstaller
  - pip
  - pip:
    - bleak