name: OpenHRV
channels:
  - conda-forge
dependencies:
  - python=3.8
  - nomkl    # necessary for building with PyInstaller on Windows, since installing numpy (pyqtgraph dependency) with MKL currently breaks pyinstaller
  - pyqtgraph=0.11.0    # pin to avoid trouble with importing pyqtgraph.graphicsItems.ViewBox.axisCtrlTemplate_pyside2 in 0.12.0
  - pyside2
  - redis-py
  - pyinstaller    # only for building
  - pip
  - pip:
    - bleak