name: manual build

on:
  workflow_dispatch    # manually triggered workflow

jobs:

  build_windows:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: "3.8"

    - name: Install dependencies
      shell: powershell
      run: |
          python -m pip install --upgrade pip
          python -m pip install bleak pyside6 numpy pyqtgraph redis pyinstaller

    - name: build with pyinstaller
      shell: powershell
      # declare PySide6 as hidden import to fix https://github.com/pyinstaller/pyinstaller/issues/5414
      run: |
        pyinstaller --hidden-import=PySide6 --onefile --icon=logo.ico OpenHRV.py

    - name: upload exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: OpenHRV_windows
        path: dist/OpenHRV.exe