name: manual build

on:
  workflow_dispatch    # manually triggered workflow

jobs:

  build_windows:

    env:
      pythonVersion: "3.8"

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
          python-version: ${{ env.pythonVersion }}

    - name: Install dependencies
      shell: powershell
      run: |
          python -m pip install --upgrade pip
          python -m pip install bleak pyside6 numpy pyqtgraph redis pyinstaller

    - name: build with pyinstaller
      shell: powershell
      # Manually adding the `plugins` directory is a temporary workaround until PyInstaller supports PySide6: https://github.com/pyinstaller/pyinstaller/issues/5414;
      # `pythonLocation` is set by the `setup-python` action.
      run: |
        ls $pythonLocation
        pyinstaller --add-data "$pythonLocation/lib/site-packages/PySide6/plugins;PySide6/plugins/" --onefile --icon=logo.ico OpenHRV.py

    - name: upload exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: OpenHRV_windows
        path: dist/OpenHRV.exe